version: '3.7'
services:
  jenkins:
    environment:
     -  AWS_ACCESS_KEY_ID=888888888
     -  AWS_SECRET_ACCESS_KEY=888888888
    container_name: jenkins_root
    image: si3mshady/jenkins-iam-root
    ports:
      - "8080:8080"
    volumes:            
      - "$PWD/jenkins_home:/var/jenkins_home"

