version: '3.7'
services:
  jenkins-root:
    environment:
     -  AWS_ACCESS_KEY_ID=AKIAZdfs3DBFQ
     -  AWS_SECRET_ACCESS_KEY=yg61YiFlaHdfBVNBCdeqT0Bxga6TVHx
    container_name: jenkins-iam-root
    image: si3mshady/jenkins-iam-root
    ports:
      - "8081:8080"        
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
        

